# Generated by Django 4.1.7 on 2023-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='hora_inscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
