# Generated by Django 4.1.7 on 2023-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantesApp', '0002_alter_participantes_hora_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='participantes',
            name='institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='observacion',
            field=models.CharField(max_length=100),
        ),
    ]
