# Generated by Django 4.1.7 on 2023-07-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantesApp', '0003_remove_participantes_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
